### ISSUE TITLE
Numerous occurrences of "Verifing"

### ISSUE THREAD

**Issue by uKER** [znetstar/aria2ui#2]
All over the code (both in constants and in UI text), there's numerous occurrences of "Verifing", which is a typo, the correct spelling being "Verifying".
Most noticeably, the text is visible in the progress bar when resuming a download.

**Comment by znetstar** [comment]
This project just wraps [ziahamza/webui-aria2](https://github.com/ziahamza/webui-aria2) and [aria2c](https://aria2.github.io/) in an electron application, so any issues related to the web ui should be directed to the appropriate project page.
